development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mera-lakshya_development
  pool: 5
  username: rahult
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mera-lakshya_test
  pool: 5
  username: rahult
  password:
  host: localhost
